# Author: Ofek Malul
# Date: 11/1/2024

version: '3.8' # Which version of compose is being used
services:
  jenkins:
    image: jenkins/jenkins:jdk17 # Jenkins controller requires Java to work
    container_name: jenkins
    privileged: true # Provides root capabilities on the host EC2.
    user: root
    ports:
      - '8080:8080' # Default port Jenkins is using
      - '50000:50000' # Port jenkins master and slave are communicating
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Enable docker socket connection to the docker daemon
